# Site settings
title: COSI Meeting Minutes
email: lannonbr@clarkson.edu
description: > # this means to ignore newlines until "baseurl:"
    This page hosts the Meeting minutes for the
    Clarkson Open Source Institute. Meetings are 
    held every Wednesday in Science Center 336
    while school is in session.
baseurl: "/meeting-minutes" # the subpath of your site, e.g. /blog/
url: "http://cosi-lab.github.io/meeting-minutes/" # the base hostname & protocol for your site
github_username:  cosi-lab

# Build settings
markdown: kramdown
